# Generated by Django 5.2.8 on 2025-11-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimEducation',
            fields=[
                ('edu_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('edu_name', models.CharField(max_length=50)),
                ('order_no', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('time_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimOccupation',
            fields=[
                ('occ_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('occ_name', models.CharField(max_length=100)),
                ('industry_code', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_occ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub', to='core.dimoccupation')),
            ],
        ),
        migrations.CreateModel(
            name='DimRegion',
            fields=[
                ('region_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('region_level', models.CharField(max_length=16)),
                ('iso_code', models.CharField(blank=True, max_length=16, null=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.dimregion')),
            ],
        ),
        migrations.CreateModel(
            name='FactEoiMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eoi_score_base', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('W_wage_norm', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('S_stability_norm', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('G_growth_satis_norm', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('source_version', models.CharField(default='v1.0', max_length=32)),
                ('data_quality_flag', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimoccupation')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimtime')),
            ],
            options={
                'unique_together': {('occ', 'time')},
            },
        ),
        migrations.CreateModel(
            name='FactFoiMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foi_score', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('E_employ_norm', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('T_training_norm', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('I_infra_norm', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('source_version', models.CharField(default='v1.0', max_length=32)),
                ('data_quality_flag', models.CharField(blank=True, max_length=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimeducation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimregion')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimtime')),
            ],
            options={
                'unique_together': {('region', 'edu', 'time')},
            },
        ),
    ]
